spring:
  application:
    name: todoapp
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: jwt

security:
  ignored: true


push:
  vapid:
    public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVjlIQDxqJ0nSzd2mXCLGt6Z7c42oEF8iKNFWf7N6b8Vx8HHrdLD-wKaZasb7wLf3bgECthAJJ1nOgpk0miQWQg
    private-key: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCArQtyn4vMqstREzAztqPYsOAXeo9O_kKjshgvKUGFQnw
    subject: mailto:amypark0@naver.com

springdoc:
  api-docs:
    enabled: true #API 문서 활성화 여부
    path: /api-docs  #API 문서 엔드포인트 변경
    groups.enabled: true  #여러 개의 API 그룹 지원할지 여부
  swagger-ui:
    enabled: true # Swagger UI 활성화 여부 (기본값: true)
    path: /swagger-ui.html  # Swagger UI 접속 경로 변경 (기본값: /swagger-ui.html)
    operationSorter: method
    tagsSorter: alpha # 태그 정렬 방식
    display-request-duration: true #요청 실행 시간 표시 여부
    doc-expansion: none #swagger ui 에서 api 설명의 기본 펼침 상태
    persistAuthorization: true #페이지 새로고침 후에도 Authorization 헤더 유지 여부
    defaultModelsExpandDepth: -1 # 모델 스키마의 기본 펼침 깊이 (-1이면 모델 펼쳐지지 않음)
  paths-to-match: # OpenAPI 문서에서 포함할 엔드포인트 패턴
    - /api/** # /api로 시작하는 모든 경로 포함
  cache:
    disabled: true # OpenAPI 문서의 캐싱 비활성화 (기본값: false)
  show-actuator: false # Spring Actuator 엔드포인트를 Swagger UI에 표시할지 여부 (기본값: false)
  servers:
    - url: http://localhost:8080 # 기본 서버 URL 설정
      description: "local 개발 환경"
    - url: https://api/example.com   # 운영 서버 URL 설정
      description: "production 서버"






