name: Java CI with Gradle

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: JDK 설정
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle 빌드
      run: |
        chmod +x ./gradlew
        ./gradlew clean build 
        ls -al build/libs

    - name: ZIP 파일 생성
      run: |
        mkdir -p deploy
        cp -r build/libs deploy/
        cp -r scripts deploy/
        cp appspec.yml deploy/
        cd deploy && zip -r ../deploy.zip .
        
    - name: aws 자격 증명 설정 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: S3 에 업로드
      run: |
        aws s3 cp deploy.zip s3://todoapp-github-actions-s3-bucket/deploy.zip      
        
    - name: CodeDeploy 실행
      run: |
        aws deploy create-deployment \
          --application-name my-codedeploy-app \
          --deployment-group-name my-codedeploy-deployment-group \
          --s3-location bucket=todoapp-github-actions-s3-bucket,key=deploy.zip,bundleType=zip \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --file-exists-behavior OVERWRITE
      

   
